
# Final NumPy Assignment
# Inputs khud se create karna hai



# Q1. Array Creation and Attributes

## Problem Statement
Create array [10,20,30,40,50] and print shape, ndim, size and dtype.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [6]:
import numpy as np

arr = np.arange(10,51,10)
arr

print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)


(5,)
1
5
int64



# Q2. Matrix Creation

## Problem Statement
Create a 3x3 NumPy matrix and print it.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [8]:
matrix = np.arange(1,10).reshape(3,3)
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]



# Q3. Indexing Practice

## Problem Statement
Print first, third and last element from an array.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [11]:
arr = np.arange(1,7)

print(arr[[1,3,-1]])

[2 4 6]



# Q4. Slicing Practice

## Problem Statement
Print elements from index 2 to 5.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [14]:
a = np.arange(10,101,10)
a
print(a[2:6])

[30 40 50 60]



# Q5. Fancy Indexing

## Problem Statement
Print selected elements using fancy indexing.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [16]:
a = np.arange(1,11)
a
print(a[[1,3,5,7]])

[2 4 6 8]



# Q6. Conditional Selection

## Problem Statement
Print values greater than 15.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [ ]:
a = np.array([2,4,43,15,32,9,3,11,60])
a
print(a[a > 15])            #give value
print(np.where(a > 15))     #give index

[43 32 60]
(array([2, 4, 8]),)



# Q7. Broadcasting

## Problem Statement
Add 10 to every element of an array.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [22]:
a = np.arange(1,7)
a
print(a+10)

[11 12 13 14 15 16]



# Q8. Aggregate Functions

## Problem Statement
Print sum, mean, max and min.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [23]:
a = np.arange(1,6)
a
print(a.sum())
print(a.mean())
print(a.max())
print(a.min())

15
3.0
5
1



# Q9. Sorting

## Problem Statement
Sort an unsorted NumPy array.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [26]:
a = np.array([1,4,2,6,3,10,8,9,16])
a
print(np.sort(a))

[ 1  2  3  4  6  8  9 10 16]



# Q10. Concatenation and Stacking

## Problem Statement
Perform concatenate and vstack on two arrays.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [39]:
a = np.arange(5,26,5)
b = np.arange(30,51,5)

print(np.concatenate([a,b]))

[ 5 10 15 20 25 30 35 40 45 50]


In [40]:
a,b
print(np.vstack((a,b)))

[[ 5 10 15 20 25]
 [30 35 40 45 50]]
